# Generated by Django 5.0.7 on 2026-01-07 23:17

import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import main.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=120)),
                ('name', models.CharField(max_length=120)),
                ('f_name', models.CharField(max_length=120)),
                ('l_name', models.CharField(max_length=120)),
                ('doe', models.DateField(default=django.utils.timezone.now)),
                ('rating', models.FloatField(default=0.0)),
                ('languages', models.JSONField(default=list)),
                ('profile', models.ImageField(blank=True, null=True, upload_to=main.models.user_profile_path)),
                ('files', models.FileField(blank=True, null=True, upload_to='user_files/')),
                ('groups', models.ManyToManyField(related_name='custom_user_set', to='auth.group')),
                ('user_permissions', models.ManyToManyField(related_name='custom_user_set_permissions', to='auth.permission')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Discussion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('files', models.FileField(blank=True, null=True, upload_to='discussion_files/')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UserDiscussion', to=settings.AUTH_USER_MODEL)),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Comments', to='main.discussion')),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=120, null=True)),
                ('description', models.TextField()),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField()),
                ('files', models.FileField(blank=True, null=True, upload_to='assignment_files/')),
                ('by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='HostAssignment', to=settings.AUTH_USER_MODEL)),
                ('doneby', models.ManyToManyField(blank=True, related_name='AssignmentUser', to=settings.AUTH_USER_MODEL)),
                ('comments', models.ManyToManyField(blank=True, related_name='AssignmentDiscussion', to='main.discussion')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=120)),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_viewed', models.BooleanField(default=False)),
                ('by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tempNotification', to=settings.AUTH_USER_MODEL)),
                ('to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UserNotification', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('rating', models.FloatField()),
                ('progress', models.IntegerField(default=0)),
                ('status', models.CharField(max_length=120)),
                ('files', models.FileField(blank=True, null=True, upload_to='project_files/')),
                ('tags', models.JSONField(blank=True, default=list)),
                ('objectives', models.JSONField(blank=True, default=list)),
                ('languages', models.JSONField(blank=True, default=list)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('hiring', models.BooleanField(default=True)),
                ('github_link', models.CharField(max_length=200)),
                ('twitter_link', models.CharField(max_length=200)),
                ('facebook_link', models.CharField(max_length=200)),
                ('instagram_link', models.CharField(max_length=200)),
                ('web_link', models.CharField(max_length=200)),
                ('assignments', models.ManyToManyField(blank=True, related_name='ProjectAssignment', to='main.assignment')),
                ('comments', models.ManyToManyField(blank=True, related_name='ProjectDiscussion', to='main.discussion')),
                ('host', models.ManyToManyField(blank=True, related_name='hosts', to=settings.AUTH_USER_MODEL)),
                ('invited', models.ManyToManyField(blank=True, related_name='invited', to=settings.AUTH_USER_MODEL)),
                ('potential_user', models.ManyToManyField(blank=True, related_name='PotentialUser', to=settings.AUTH_USER_MODEL)),
                ('user', models.ManyToManyField(blank=True, related_name='users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='discussion',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projectdiscuss', to='main.project'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AssignmentProject', to='main.project'),
        ),
        migrations.AddField(
            model_name='user',
            name='projects',
            field=models.ManyToManyField(related_name='UserProjects', to='main.project'),
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('files', models.FileField(blank=True, null=True, upload_to='submission_files/')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SubmissionAssignment', to='main.assignment')),
                ('by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SubmissionUser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='submissions',
            field=models.ManyToManyField(related_name='UserSubmissions', to='main.submission'),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('deadline', models.DateTimeField()),
                ('description', models.TextField()),
                ('status', models.TextField(default='Active')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.project')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TeamProject', to='main.project')),
                ('users', models.ManyToManyField(related_name='TeamUser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
